/* ANIM OS — KNOWLEDGE VAULT v2
 * Cinematic black library: books live on shelves, fly forward, open wide,
 * and the corresponding DOM content is clipped INSIDE one open page.
 */
(() => {
'use strict';
const T=window.THREE,canvas=document.getElementById('story-canvas'),main=document.getElementById('main');
if(!T||!canvas||!main||window.__animKnowledgeVault)return; window.__animKnowledgeVault=true;
const clamp=(v,a=0,b=1)=>Math.max(a,Math.min(b,v));
const ease=v=>v<.5?4*v*v*v:1-Math.pow(-2*v+2,3)/2;
const range=(v,a,b)=>ease(clamp((v-a)/(b-a)));
const style=document.createElement('style'); style.textContent=`
html,body,#main{background:#000!important}#story-canvas{position:fixed!important;inset:0!important;width:100vw!important;height:100vh!important;z-index:0!important;background:#000!important}
#main{min-height:900vh!important;background:transparent!important}.#main .container{min-height:900vh!important}
#main .container{position:relative!important;height:900vh!important;z-index:3!important;pointer-events:none!important;padding:0!important;margin:0!important;max-width:none!important}
#main .container>section.vault-ui{position:fixed!important;left:50%!important;top:50%!important;width:min(700px,calc(100vw - 34px))!important;height:min(390px,55vh)!important;max-height:none!important;overflow:hidden!important;z-index:20!important;opacity:0;pointer-events:none;transform:translate(-50%,-50%) scale(.18);transform-origin:center!important;will-change:transform,opacity,filter!important;border-radius:4px!important}
.vault-page-mask{position:fixed;inset:0;z-index:19;pointer-events:none}.vault-title{position:fixed;top:22px;left:50%;transform:translateX(-50%);z-index:8;color:rgba(255,255,255,.4);font:600 9px/1 Arial,sans-serif;letter-spacing:.45em;white-space:nowrap;pointer-events:none}.vault-hint{position:fixed;right:20px;bottom:26px;z-index:8;color:rgba(255,255,255,.28);font:600 8px/1 Arial,sans-serif;letter-spacing:.28em;writing-mode:vertical-rl;pointer-events:none}
@media(max-width:700px){#main,.#main .container{min-height:1100vh!important;height:1100vh!important}#main .container{height:1100vh!important}.#main .container>section.vault-ui{width:calc(100vw - 50px)!important;height:min(330px,58vh)!important}.vault-title{font-size:7px;top:15px}.vault-hint{right:8px}}
`;document.head.appendChild(style);
const ids=['profile','projects','contact','ai-section'];ids.forEach(id=>{const e=document.getElementById(id);if(e)e.classList.add('vault-ui')});
const title=document.createElement('div');title.className='vault-title';title.textContent='ANIM OS  •  KNOWLEDGE VAULT';document.body.appendChild(title);
const hint=document.createElement('div');hint.className='vault-hint';hint.textContent='SCROLL TO EXPLORE';document.body.appendChild(hint);
const mobile=matchMedia('(max-width:700px)').matches;
const renderer=new T.WebGLRenderer({canvas,antialias:!mobile,alpha:false,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio||1,mobile?1.2:1.5));renderer.setSize(innerWidth,innerHeight);renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=.92;
const scene=new T.Scene();scene.background=new T.Color(0x000000);scene.fog=new T.FogExp2(0x000000,.027);const camera=new T.PerspectiveCamera(48,innerWidth/innerHeight,.1,140);const world=new T.Group();scene.add(world);
// Deep black library architecture.
const library=new T.Group();library.position.z=-17;world.add(library);const wood=new T.MeshStandardMaterial({color:0x16100d,roughness:.62,metalness:.12}),darkWood=new T.MeshStandardMaterial({color:0x080706,roughness:.82}),edge=new T.MeshStandardMaterial({color:0x59616a,roughness:.25,metalness:.72});
const floor=new T.Mesh(new T.PlaneGeometry(52,70),new T.MeshStandardMaterial({color:0x010101,roughness:.96}));floor.rotation.x=-Math.PI/2;floor.position.set(0,-4,7);world.add(floor);
const back=new T.Mesh(new T.PlaneGeometry(52,34),darkWood);back.position.set(0,6,-18);library.add(back);
// Tall shelving towers, clearly visible but kept dark.
for(let x=-14;x<=14;x+=7){const tower=new T.Group();tower.position.x=x;library.add(tower);const sideL=new T.Mesh(new T.BoxGeometry(.32,22,1.2),wood);sideL.position.x=-3.25;tower.add(sideL);const sideR=sideL.clone();sideR.position.x=3.25;tower.add(sideR);for(let r=0;r<9;r++){const y=-3.5+r*2.35;const plank=new T.Mesh(new T.BoxGeometry(6.8,.22,1.15),wood);plank.position.y=y;tower.add(plank);const trim=new T.Mesh(new T.BoxGeometry(6.8,.045,.1),edge);trim.position.set(0,y+.14,.57);tower.add(trim)}}
// Filler books are physically packed into the shelves.
const fillerGeo=new T.BoxGeometry(.34,1.72,.78),fillerMat=new T.MeshStandardMaterial({color:0x292a2c,roughness:.66,metalness:.12});const count=mobile?180:360,filler=new T.InstancedMesh(fillerGeo,fillerMat,count),dummy=new T.Object3D();for(let i=0;i<count;i++){const shelfRow=i%9,tower=Math.floor(i/Math.max(1,Math.ceil(count/9*1/5))),col=i%5;const x=-14+tower*7-2.65+col*1.28+(Math.random()-.5)*.2;dummy.position.set(x,-2.55+shelfRow*2.35,-16.25+(Math.random()-.5)*.06);dummy.rotation.z=(Math.random()-.5)*.055;dummy.scale.set(.72+Math.random()*.5,.72+Math.random()*.48,.86+Math.random()*.18);dummy.updateMatrix();filler.setMatrixAt(i,dummy.matrix)}filler.instanceMatrix.needsUpdate=true;library.add(filler);
// Shelf pools of warm light keep the library readable without changing the black mood.
for(let x=-14;x<=14;x+=7){const lamp=new T.PointLight(0xffd8a0,.9,7,2);lamp.position.set(x,4,-13);library.add(lamp)}
scene.add(new T.HemisphereLight(0x29313b,0x000000,.28));const key=new T.PointLight(0xffffff,2.2,32,1.7);key.position.set(0,4,-4);world.add(key);const rim=new T.PointLight(0x6b8cff,1.25,25,2);rim.position.set(-10,3,-10);world.add(rim);
const dustCount=mobile?90:220,pos=new Float32Array(dustCount*3);for(let i=0;i<dustCount;i++){pos[i*3]=(Math.random()-.5)*30;pos[i*3+1]=-3+Math.random()*15;pos[i*3+2]=-1-Math.random()*27}const dg=new T.BufferGeometry();dg.setAttribute('position',new T.BufferAttribute(pos,3));world.add(new T.Points(dg,new T.PointsMaterial({color:0xb6c0ca,size:.045,transparent:true,opacity:.22,depthWrite:false})));
class HeroBook{constructor(cfg){this.base=cfg.pos.clone();this.group=new T.Group();this.group.position.copy(this.base);library.add(this.group);const cover=new T.MeshStandardMaterial({color:cfg.color,roughness:.22,metalness:.42,emissive:cfg.color,emissiveIntensity:.06}),paper=new T.MeshStandardMaterial({color:0xf3efe4,roughness:.7,side:T.DoubleSide}),inside=new T.MeshStandardMaterial({color:0xe7e1d5,roughness:.8}),silver=new T.MeshStandardMaterial({color:0xbfc8d1,roughness:.16,metalness:.92});
this.back=new T.Mesh(new T.BoxGeometry(3.55,5.25,.18),cover);this.group.add(this.back);
this.pages=new T.Group();this.pages.position.z=.2;this.group.add(this.pages);for(let i=0;i<24;i++){const p=new T.Mesh(new T.PlaneGeometry(3.3,5.02),i===12?inside:paper);p.position.z=i*.008;this.pages.add(p)}
this.frontPivot=new T.Group();this.frontPivot.position.set(-1.76,0,.34);this.group.add(this.frontPivot);this.front=new T.Mesh(new T.BoxGeometry(3.55,5.25,.18),cover);this.front.position.x=1.76;this.frontPivot.add(this.front);this.spine=new T.Mesh(new T.BoxGeometry(.2,5.4,.3),silver);this.spine.position.set(-1.67,0,.15);this.group.add(this.spine);
this.titleBand=new T.Mesh(new T.BoxGeometry(2.15,.07,.05),silver);this.titleBand.position.set(1.76,-.62,.44);this.frontPivot.add(this.titleBand);
// Anchor is centered on the RIGHT page: DOM is clipped to this page's rectangle by a CSS clip-path.
this.anchor=new T.Object3D();this.anchor.position.set(.82,.02,.49);this.group.add(this.anchor);this.glow=new T.PointLight(cfg.color,0,9,2);this.group.add(this.glow)}
update(extract,open,returning){const e=ease(extract),o=ease(open),r=ease(returning);this.group.position.x=this.base.x+Math.sin(e*Math.PI)*.3;this.group.position.y=this.base.y+Math.sin(e*Math.PI)*.16;this.group.position.z=this.base.z+e*(1-r)*9;this.group.scale.setScalar(1+e*.48*(1-r));this.group.rotation.y=e*.08;this.group.rotation.x=Math.sin(e*Math.PI)*-.045;this.frontPivot.rotation.y=-o*2.72;this.pages.children.forEach((p,i)=>{const t=i/(this.pages.children.length-1);p.position.x=(t-.5)*o*.7;p.rotation.y=(t-.5)*o*.34;p.position.z=.02+i*.006+Math.sin(t*Math.PI)*o*.2});this.glow.intensity=o*2.2}}
const configs=[{id:'profile',pos:new T.Vector3(-8,-1.1,0),color:0x1687ff},{id:'projects',pos:new T.Vector3(-4,1.25,0),color:0x19c86a},{id:'contact',pos:new T.Vector3(0,-1.1,0),color:0xff3038},{id:'ai-section',pos:new T.Vector3(4,1.25,0),color:0xffd21c},{id:'future',pos:new T.Vector3(8,-1.1,0),color:0x1687ff}],books=configs.map(c=>new HeroBook(c));
// Camera approaches the shelves instead of presenting a floating black void.
const cameraPath=new T.CatmullRomCurve3([new T.Vector3(0,3.2,29),new T.Vector3(-3,2.5,20),new T.Vector3(2,2.1,12),new T.Vector3(-5,1.7,7),new T.Vector3(-8,1.15,3.2),new T.Vector3(-3,.95,3),new T.Vector3(1,1.1,3),new T.Vector3(5,1.45,3),new T.Vector3(8,1.15,3),new T.Vector3(0,2.6,16)]);
const targets=[new T.Vector3(0,0,-17),new T.Vector3(-8,-.4,-17),new T.Vector3(-4,.8,-17),new T.Vector3(0,-.4,-17),new T.Vector3(4,.8,-17),new T.Vector3(8,-.4,-17),new T.Vector3(0,2,-17)];
function positionPopup(el,book,visible){if(!el)return;const a=book.anchor.getWorldPosition(new T.Vector3()).project(camera);const x=(a.x*.5+.5)*innerWidth,y=(-a.y*.5+.5)*innerHeight;el.style.left=`${x}px`;el.style.top=`${y}px`;el.style.transform=`translate(-50%,-50%) scale(${visible})`;
// Clip the HTML content to a single page. The panel's center is aligned to the right-page anchor.
el.style.clipPath='inset(0 0 0 0 round 4px)';el.style.webkitClipPath='inset(0 0 0 0 round 4px)';}
function setPopup(active,book,local){ids.forEach((id,i)=>{const el=document.getElementById(id);if(!el)return;if(i===active){const reveal=range(local,.22,.43),hold=range(local,.43,.67),hide=range(local,.67,.88);const vis=Math.max(0,Math.min(1,reveal,1-hide));el.style.opacity=vis;el.style.filter=`blur(${12*(1-Math.max(reveal,hold))}px)`;positionPopup(el,book,.2+.8*Math.max(reveal,hold)*(1-hide));el.style.pointerEvents=vis>.75?'auto':'none'}else{el.style.opacity=0;el.style.pointerEvents='none';el.style.transform='translate(-50%,-50%) scale(.2)'}})}
let progress=0,target=0;const readScroll=()=>{const max=Math.max(1,document.documentElement.scrollHeight-innerHeight);target=clamp(scrollY/max)};addEventListener('scroll',readScroll,{passive:true});readScroll();
function frame(){progress+=(target-progress)*.075;const p=progress,pos=cameraPath.getPointAt(p);camera.position.lerp(pos,.095);const ti=p*(targets.length-1),a=Math.floor(ti),b=Math.min(targets.length-1,a+1),q=ti-a,look=targets[a].clone().lerp(targets[b],q);camera.lookAt(look);const zones=[.09,.29,.49,.69];let active=-1;books.forEach((book,i)=>{if(i>=4){book.update(0,0,1);return}const local=clamp((p-(zones[i]-.075))/.22),extract=range(local,0,.22),open=range(local,.20,.43),returning=range(local,.69,1);book.update(extract,open,returning);if(local>.07&&local<.93)active=i});if(active>=0)setPopup(active,books[active],clamp((p-(zones[active]-.075))/.22));else ids.forEach(id=>{const e=document.getElementById(id);if(e){e.style.opacity=0;e.style.pointerEvents='none'}});renderer.render(scene,camera);requestAnimationFrame(frame)}
addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setPixelRatio(Math.min(devicePixelRatio||1,matchMedia('(max-width:700px)').matches?1.2:1.5));renderer.setSize(innerWidth,innerHeight)},{passive:true});frame();
})();
