/* Clean cinematic visual layer: black void -> star ignition -> light beam -> constellation. */
(()=>{
'use strict';
const styles=()=>{if(document.getElementById('cp-style'))return;const s=document.createElement('style');s.id='cp-style';s.textContent=`html,body{background:#000!important}body:before,body:after{display:none!important}#story-canvas{display:none!important;visibility:hidden!important;opacity:0!important}#cinematic-canvas{position:fixed;inset:0;width:100vw;height:100vh;z-index:0;display:block;pointer-events:none;background:#000}#main{background:transparent!important;position:relative;z-index:1}.orb{opacity:.05!important}.glass-panel{background:rgba(5,10,18,.38)!important;backdrop-filter:blur(10px) saturate(120%)!important;-webkit-backdrop-filter:blur(10px) saturate(120%)!important;box-shadow:0 20px 60px rgba(0,0,0,.2),inset 0 1px 1px rgba(255,255,255,.1)!important}#ai-section{width:min(760px,100%)!important;min-height:0!important;height:auto!important;margin:65px auto 30px!important;padding:22px!important;justify-content:flex-start!important}#ai-section #chat-box{height:210px!important;min-height:0!important;margin:18px 0!important}@media(max-width:650px){#cinematic-canvas{height:100dvh}#ai-section{width:calc(100% - 4px)!important;margin:50px auto 25px!important;padding:17px!important;border-radius:20px!important}#ai-section #chat-box{height:180px!important;margin:14px 0!important}.glass-panel{background:rgba(4,9,17,.3)!important}}`;document.head.appendChild(s)};
const radial=THREE=>{const c=document.createElement('canvas');c.width=c.height=256;const x=c.getContext('2d'),g=x.createRadialGradient(128,128,0,128,128,128);g.addColorStop(0,'#fff');g.addColorStop(.025,'rgba(210,250,255,.95)');g.addColorStop(.12,'rgba(60,220,255,.45)');g.addColorStop(.38,'rgba(40,160,255,.1)');g.addColorStop(1,'rgba(0,0,0,0)');x.fillStyle=g;x.fillRect(0,0,256,256);return new THREE.CanvasTexture(c)};
const beamTex=THREE=>{const c=document.createElement('canvas');c.width=32;c.height=512;const x=c.getContext('2d'),g=x.createLinearGradient(0,0,32,0);g.addColorStop(0,'rgba(0,0,0,0)');g.addColorStop(.34,'rgba(60,210,255,.02)');g.addColorStop(.5,'rgba(225,252,255,.75)');g.addColorStop(.66,'rgba(60,210,255,.02)');g.addColorStop(1,'rgba(0,0,0,0)');x.fillStyle=g;x.fillRect(0,0,32,512);return new THREE.CanvasTexture(c)};
window.initNarrativeWorld=()=>{
if(!window.THREE||!window.gsap||!window.ScrollTrigger)return;if(document.getElementById('cinematic-canvas'))return;styles();gsap.registerPlugin(ScrollTrigger);
const mobile=matchMedia('(max-width:700px)').matches,reduced=matchMedia('(prefers-reduced-motion:reduce)').matches,canvas=document.createElement('canvas');canvas.id='cinematic-canvas';document.body.insertBefore(canvas,document.body.firstChild);
const scene=new THREE.Scene();scene.fog=new THREE.FogExp2(0x000000,mobile?.008:.0055);const camera=new THREE.PerspectiveCamera(52,innerWidth/innerHeight,.1,700);camera.position.z=38;const renderer=new THREE.WebGLRenderer({canvas,alpha:false,antialias:!mobile,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,mobile?1.2:1.6));renderer.setSize(innerWidth,innerHeight);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=.72;
const world=new THREE.Group();scene.add(world);const clock=new THREE.Clock(),state={p:0,v:0,tv:0,mx:0,my:0,tx:0,ty:0};const light=new THREE.PointLight(0x8eeaff,0,90,2);light.position.z=2;scene.add(light);scene.add(new THREE.AmbientLight(0xffffff,.025));
const count=reduced?300:mobile?650:1700,pos=new Float32Array(count*3);for(let i=0;i<count;i++){const j=i*3,r=18+Math.random()*105,a=Math.random()*Math.PI*2;pos[j]=Math.cos(a)*r;pos[j+1]=(Math.random()-.5)*80;pos[j+2]=-10-Math.random()*210}const sg=new THREE.BufferGeometry();sg.setAttribute('position',new THREE.BufferAttribute(pos,3));const sm=new THREE.PointsMaterial({color:0xbcefff,size:mobile?.035:.045,transparent:true,opacity:.02,depthWrite:false,blending:THREE.AdditiveBlending});const stars=new THREE.Points(sg,sm);world.add(stars);
const star=new THREE.Sprite(new THREE.SpriteMaterial({map:radial(THREE),transparent:true,opacity:0,depthWrite:false,blending:THREE.AdditiveBlending}));world.add(star);const core=new THREE.Mesh(new THREE.SphereGeometry(.08,8,8),new THREE.MeshBasicMaterial({color:0xffffff,transparent:true,opacity:0}));world.add(core);
const bg=new THREE.Group();world.add(bg);const tex=beamTex(THREE),angles=[0,Math.PI/2,Math.PI/4,-Math.PI/4],beams=[];angles.forEach((a,i)=>{const m=new THREE.MeshBasicMaterial({map:tex,color:i?0x62dcff:0xdffcff,transparent:true,opacity:0,depthWrite:false,blending:THREE.AdditiveBlending,side:THREE.DoubleSide}),b=new THREE.Mesh(new THREE.PlaneGeometry(.55,35),m);b.rotation.z=a;bg.add(b);beams.push(b)});
const ng=new THREE.Group();world.add(ng);const nodes=[],ncount=mobile?8:14;for(let i=0;i<ncount;i++){const a=i/ncount*Math.PI*2,r=5.5+(i%4)*1.5,m=new THREE.MeshBasicMaterial({color:0xa9efff,transparent:true,opacity:0});const n=new THREE.Mesh(new THREE.SphereGeometry(.07,6,6),m);n.position.set(Math.cos(a)*r,Math.sin(a)*r*.62,-5-(i%3)*1.5);ng.add(n);nodes.push(n)}const lp=[];nodes.forEach(n=>lp.push(0,0,-2,n.position.x,n.position.y,n.position.z));const lg=new THREE.BufferGeometry();lg.setAttribute('position',new THREE.Float32BufferAttribute(lp,3));const lm=new THREE.LineBasicMaterial({color:0x65ddff,transparent:true,opacity:0,depthWrite:false,blending:THREE.AdditiveBlending});ng.add(new THREE.LineSegments(lg,lm));
ScrollTrigger.create({trigger:document.getElementById('main'),start:'top top',end:'bottom bottom',scrub:1.25,invalidateOnRefresh:true,onUpdate:s=>{state.p=s.progress;state.tv=THREE.MathUtils.clamp(s.getVelocity()/2500,-1,1)}});
['profile','contact','ai-section'].forEach(id=>{const e=document.getElementById(id);if(e&&!reduced)gsap.fromTo(e,{y:28,rotateX:2.5,scale:.992},{y:0,rotateX:0,scale:1,ease:'none',scrollTrigger:{trigger:e,start:'top 88%',end:'top 52%',scrub:1.1}})});
document.querySelectorAll('.contact-card,.liquid-btn').forEach(e=>{e.addEventListener('pointerenter',()=>gsap.to(light,{intensity:mobile?4:7,duration:.3,overwrite:true}));e.addEventListener('pointerleave',()=>gsap.to(light,{intensity:0,duration:.45,overwrite:true}))});addEventListener('pointermove',e=>{state.tx=e.clientX/innerWidth-.5;state.ty=e.clientY/innerHeight-.5},{passive:true});
addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setPixelRatio(Math.min(devicePixelRatio,innerWidth<700?1.2:1.6));renderer.setSize(innerWidth,innerHeight);ScrollTrigger.refresh()},{passive:true});
function update(t){const p=state.p,ignite=THREE.MathUtils.smoothstep(p,.035,.30),awaken=THREE.MathUtils.smoothstep(p,.12,.38),connection=THREE.MathUtils.smoothstep(p,.55,.78),intelligence=THREE.MathUtils.smoothstep(p,.74,.92),expand=THREE.MathUtils.smoothstep(p,.9,1);core.material.opacity=ignite;core.scale.setScalar(.6+ignite*1.8);star.material.opacity=.12*ignite;star.scale.setScalar(.7+ignite*5.2);light.intensity=ignite*(mobile?7:14)+intelligence*(mobile?2:4);bg.scale.y=.18+ignite*1.35;beams.forEach((b,i)=>{b.material.opacity=ignite*(i?.045:.22)*(1+.18*Math.sin(t*1.4+i));b.rotation.z=angles[i]+Math.sin(t*.12+i)*.012});sm.opacity=.018+awaken*.075+expand*.035;ng.position.z=THREE.MathUtils.lerp(5,-2,connection);ng.rotation.z=connection*Math.PI*.8;nodes.forEach((n,i)=>{n.material.opacity=THREE.MathUtils.clamp((connection-i/ncount*.38)*1.35,0,1)*.48;n.scale.setScalar(.7+intelligence*.8)});lm.opacity=connection*.16;camera.position.z=THREE.MathUtils.lerp(38,52,expand);state.v=THREE.MathUtils.lerp(state.v,state.tv,.07);state.mx=THREE.MathUtils.lerp(state.mx,state.tx,.045);state.my=THREE.MathUtils.lerp(state.my,state.ty,.045);camera.position.x=THREE.MathUtils.lerp(camera.position.x,state.mx*1.15,.035);camera.position.y=THREE.MathUtils.lerp(camera.position.y,-state.my*.8,.035);world.rotation.z+=state.v*.00035;camera.lookAt(0,0,-5)}
function render(){update(clock.getElapsedTime());renderer.render(scene,camera);requestAnimationFrame(render)}ScrollTrigger.refresh();render();};
})();
